#!/bin/bash
script="$1"
shift
export LARCENY_ROOT=/usr/local/lib/larceny
if head -n1 "$script" | grep -q -e '^#! ' -e '^#!/'; then
  # Remove the shebang.
  exec /usr/local/lib/larceny/larceny -r6rs -program "$script" -ignore1 -- "$@"
else
  exec /usr/local/lib/larceny/larceny -r6rs -program "$script" -- "$@"
fi
