#!/bin/bash
# The IRONSCHEME_LIBRARY_PATH variable is non-standard.
set -eu
runtime=mono
exe=ironscheme
flags=()
case $(basename "$0") in
scheme-banner) exe=IronScheme.Console-v4.exe ;;
*) flags+=(/nologo) ;;
esac
flags+=(--)
IFS=':' read -ra paths <<<"${IRONSCHEME_LIBRARY_PATH:-}"
for path in "${paths[@]}"; do flags+=(-I "$path"); done
exec "$runtime" "/usr/local/IronScheme/$exe" "${flags[@]}" "$@"
