#!/bin/bash
# The IRONSCHEME_LIBRARY_PATH variable is non-standard.
set -eu

pathflags=()
IFS=':' read -ra paths <<< "${IRONSCHEME_LIBRARY_PATH:-}"
for path in "${paths[@]}"; do
  pathflags+=(-I "$path")
done

exec mono /usr/local/IronScheme/IronScheme.Console-v4.exe \
  /nologo -- "${pathflags[@]}" "$@"
