#!/bin/sh
# ksi gets its prompt from the zeroth command line argument. We need
# this wrapper to make that "ksi>". If we just made a symbolic link
# from ksi to scheme-banned, then running scheme-banner would make the
# prompt say "scheme-banner>".
exec ksi "$@"
