#!/bin/bash
# The IRONSCHEME_LIBRARY_PATH variable is non-standard.
set -eu
runtime=dotnet
exe=IronScheme.ConsoleCore.dll
flags=()
case $(basename "$0") in
scheme-banner) ;;
*) flags+=(/nologo) ;;
esac
flags+=(--)
IFS=':' read -ra paths <<<"${IRONSCHEME_LIBRARY_PATH:-}"
for path in "${paths[@]}"; do flags+=(-I "$path"); done
exec "$runtime" "/usr/local/IronScheme/$exe" "${flags[@]}" "$@"
