#!/bin/bash
# The IRONSCHEME_LIBRARY_PATH variable is non-standard.
set -eu

pathflags=()
IFS=':' read -ra paths <<<"${IRONSCHEME_LIBRARY_PATH:-}"
for path in "${paths[@]}"; do
  pathflags+=(-I "$path")
done

case $(basename "$0") in
    scheme-banner)
        exec dotnet "/usr/local/IronScheme/IronScheme.ConsoleCore.dll" -- "${pathflags[@]}" "$@"
        ;;
    *)
        exec dotnet "/usr/local/IronScheme/IronScheme.ConsoleCore.dll" /nologo -- "${pathflags[@]}" "$@"
esac
